services:
  - type: worker
    name: midas-fon-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-tur
      pip install -r requirements.txt
    startCommand: python bot.py
